<?
// visokios konstantos, kad servas veiktu normaliai
// jeigu matote sita faila, reiskias kazkur palikau saugumo skyle :)
// nors siaip tai ju visai ir neieskojau

// esminis dalykas, nuspresti kur mes esame,
// ant internekos serverio ar pas mrfrost namie
// $interneka = 1;
// o gal shiaip apgreidas parejo

// nu cia imagemagikas kad veiktu
$convertimages = 1;

 
// kiek thumbnailu viename puslapyje
$th_kiek = 10;
// kiek anscii viename puslapyje
$an_kiek = 20;
?>
